// Mocks generated by Mockito 5.3.2 from annotations
// in news_apps/test/feature/home/helpers/home_test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:news_apps/core/core.dart' as _i2;
import 'package:news_apps/features/home/data/models/news_response.dart' as _i6;
import 'package:news_apps/features/home/data/remote/news_api_service.dart'
    as _i7;
import 'package:news_apps/features/home/data/remote/news_remote_data_source.dart'
    as _i4;
import 'package:retrofit/retrofit.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDataState_0<T> extends _i1.SmartFake implements _i2.DataState<T> {
  _FakeDataState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpResponse_1<T> extends _i1.SmartFake
    implements _i3.HttpResponse<T> {
  _FakeHttpResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NewsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsRemoteDataSource extends _i1.Mock
    implements _i4.NewsRemoteDataSource {
  MockNewsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.DataState<List<_i6.ArticleModel>>> getTopHeadlines() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopHeadlines,
          [],
        ),
        returnValue: _i5.Future<_i2.DataState<List<_i6.ArticleModel>>>.value(
            _FakeDataState_0<List<_i6.ArticleModel>>(
          this,
          Invocation.method(
            #getTopHeadlines,
            [],
          ),
        )),
      ) as _i5.Future<_i2.DataState<List<_i6.ArticleModel>>>);
}

/// A class which mocks [NewsApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsApiService extends _i1.Mock implements _i7.NewsApiService {
  MockNewsApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.HttpResponse<_i6.NewsResponse>> getTopHeadlines(
    String? country,
    int? page,
    int? pageSize,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopHeadlines,
          [
            country,
            page,
            pageSize,
          ],
        ),
        returnValue: _i5.Future<_i3.HttpResponse<_i6.NewsResponse>>.value(
            _FakeHttpResponse_1<_i6.NewsResponse>(
          this,
          Invocation.method(
            #getTopHeadlines,
            [
              country,
              page,
              pageSize,
            ],
          ),
        )),
      ) as _i5.Future<_i3.HttpResponse<_i6.NewsResponse>>);
}
